Added Tests for testing the content rendered on the page library
itggot-TE4/Yabs pull request #426
Opened 2020-12-10 15:20 UTC by te4-andre-skvarc

## ⚙️ What issue did you implement or fix?
Fixes #425 

## 📜 Summary
- Added a simple test to check the rendered content on the library page.

## 📝 Type of change

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-12-10 15:36 UTC, itggot-linus-styren requested changes
Nice TDD, I like what I see. Please don't commit all the "examples", makes this PR hard to review. Also looks like you ran cypress from the incorrect folder.

Reminder to run git pull --rebase origin develop before creating PR to avoid complaints about problems already solved. This time you can just ignore it, since it will not be a problem on develop branch.

2020-12-11 10:48 UTC, itggot-linus-styren approved these changes
LGTM, maybe some more functionality could be tested in the future. Consider reading this article: https://blog.logrocket.com/how-to-write-useful-end-to-end-tests-with-cypress/

You may need to change the title from DataTable to table to not break other tests, this was changed here by @te4-adrian-almetun-smeds :
https://github.com/itggot-TE4/Yabs/blame/develop/frontend/src/components/ListComponent.vue#L2

2020-12-11 11:10 UTC, te4-adrian-almetun-smeds requested changes
This commit will indeed break our other test due to it overwriting the data tag on the library card.

See my comments to resolve this.

2020-12-11 11:10 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/ListComponent.vue
> +  <v-card data-cy="DataTable">
Rebase on the dev branch in order to get the table data tag

2020-12-11 11:10 UTC, te4-adrian-almetun-smeds commented on frontend/cypress/integration/LibraryTest.js
> +        cy.get('[data-cy=DataTable]')
```suggestion
        cy.get('[data-cy=table]')
```

Here we can use the `data-cy` tag that has already been defined.

2020-12-11 11:10 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/ReturnLoanComponent.vue
> +    <v-card data-cy="FirstCard">
As this is a reusable component, maybe we should name the data tag something related to the component name. Perhaps `returnLoanCard` can be used.

2020-12-11 11:10 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/LibraryLoanComponent.vue
> +    <v-card data-cy="SecondCard">
As this is a reusable component, maybe we should name the data tag something related to the component name. Perhaps `libraryLoanCard` can be used.

2020-12-11 11:15 UTC, Linkaan commented on frontend/src/components/ListComponent.vue
> +  <v-card data-cy="DataTable">
I suggest to simply cherry-pick 4b3e159a0a2006e7e777db1d47dc7fe0becdb51a instead and then resolve conflict.

2020-12-11 11:37 UTC, te4-david-jensen commented on frontend/src/components/LibraryLoanComponent.vue
> +    <v-card data-cy="SecondCard">
```suggestion
    <v-card data-cy="borrowCard">
```

2020-12-11 11:38 UTC, te4-david-jensen commented on frontend/cypress/integration/LibraryTest.js
> +        cy.get('[data-cy=SecondCard]')
```suggestion
        cy.get('[data-cy=borrowCard]')
```

2020-12-11 11:38 UTC, te4-david-jensen commented on frontend/cypress/integration/LibraryTest.js
> +        cy.get('[data-cy=FirstCard]')
```suggestion
        cy.get('[data-cy=returnCard]')
```

2020-12-11 11:39 UTC, te4-david-jensen commented on frontend/src/components/ReturnLoanComponent.vue
> +    <v-card data-cy="FirstCard">
```suggestion
    <v-card data-cy="returnCard">
```

2020-12-11 11:40 UTC, te4-david-jensen commented on frontend/src/components/LibraryLoanComponent.vue
> +    <v-card data-cy="SecondCard">
👍

2020-12-11 11:40 UTC, te4-david-jensen commented on frontend/src/components/ReturnLoanComponent.vue
> +    <v-card data-cy="FirstCard">
👍

2020-12-11 12:15 UTC, te4-david-jensen approved these changes
Looks good! 👍  :shipit:

2020-12-11 12:53 UTC, te4-adrian-almetun-smeds requested changes
Looks good. Just remove some empty lines and we are good to merge! :+1:

2020-12-11 12:53 UTC, te4-adrian-almetun-smeds commented on frontend/cypress/integration/createTitleAndBooks.js
> +
```suggestion

```

2020-12-11 12:53 UTC, te4-adrian-almetun-smeds commented on frontend/cypress/integration/LibraryTest.js
> +
```suggestion
```

2020-12-11 12:53 UTC, te4-adrian-almetun-smeds commented on frontend/cypress/integration/LibraryTest.js
> +
```suggestion
```

2020-12-11 12:53 UTC, te4-adrian-almetun-smeds commented on frontend/cypress/integration/LibraryTest.js
> +
```suggestion
```

2020-12-11 13:04 UTC, te4-adrian-almetun-smeds approved these changes
LGTM 👍

2020-12-11 13:05 UTC, merged