admin/users load all users now instead of only teachers
itggot-TE4/Yabs pull request #435
Opened 2020-12-11 11:53 UTC by te4-alexander-nylundgomes

## ⚙️ What issue did you implement or fix?
Fixes #418 

## 📜 Summary
- Added the ability to view all users in /admin/users instead of only teachers.

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Could use some testing

2020-12-11 15:31 UTC, itggot-linus-styren commented
To make integration tests pass, please cherry-pick commits from #434 (23dcfd71bf646111fed2d97c7cc15dedcfbbc183 and 9003ce0cb508cd220c9262a4bf184e3ece6daf68)
```
git fetch --all
git cherry-pick 23dcfd7
git cherry-pick 9003ce0
git push
```

2020-12-11 15:39 UTC, itggot-linus-styren commented
Just for some context, the issue that introduced this change is this one: #325

At the time it was not a feature to be able to change roles of students, only staff members.

Perhaps it should be changed so admin can see all users, teachers can see their students and students don't have access to this page.

2020-12-15 08:56 UTC, te4-alexander-kjellberg requested changes
Remove (unnecessary..?) commented code on rows 64 -> 71?

2020-12-15 09:17 UTC, Te4-Jacob-sandstrom requested changes

2020-12-15 09:17 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/AdminUsersView.vue
> +  // }
```suggestion
```

2020-12-15 09:21 UTC, Te4-Jacob-sandstrom approved these changes

2020-12-15 09:32 UTC, te4-adrian-almetun-smeds requested changes

2020-12-15 09:32 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/AdminUsersView.vue
>     */
```suggestion
```

2020-12-15 09:32 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/AdminUsersView.vue
> +   * This function loads all the users
```suggestion
   * This function returns all users
```

2020-12-15 09:34 UTC, te4-adrian-almetun-smeds approved these changes
I will approve this :+1: :shipit:

2020-12-15 09:34 UTC, Te4-Jacob-sandstrom requested changes

2020-12-15 09:34 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/AdminUsersView.vue
> +   */
```suggestion
```

2020-12-15 09:35 UTC, Te4-Jacob-sandstrom requested changes

2020-12-15 09:35 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/AdminUsersView.vue
>     */
```suggestion
```

2020-12-15 09:37 UTC, Te4-Jacob-sandstrom approved these changes

2020-12-15 09:39 UTC, te4-alexander-kjellberg approved these changes
Looks good :ok_woman:

2020-12-15 09:41 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/AdminUsersView.vue
>    /**
```suggestion
```

Fix for syntax errors

2020-12-15 10:06 UTC, merged