Test if CardFormComponent is present in view
itggot-TE4/Yabs pull request #442
Opened 2020-12-11 13:41 UTC by Te4-Jacob-sandstrom

## ⚙️ What issue did you implement or fix?
Fixes #431

## 📜 Summary
- tests if AdminCardView has component: CardFormComponent.vue

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

2020-12-11 15:29 UTC, itggot-linus-styren commented
To make integration tests pass, please cherry-pick commits from #434 (23dcfd71bf646111fed2d97c7cc15dedcfbbc183 and 9003ce0cb508cd220c9262a4bf184e3ece6daf68)
```
git fetch --all
git cherry-pick 23dcfd7
git cherry-pick 9003ce0
git push
```

2020-12-11 15:36 UTC, te4-adrian-almetun-smeds requested changes
Other than having some excessive whitespace this looks good. Even basic tests are tests we need :+1:

2020-12-11 15:36 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/AdminCardView.spec.ts
> +
```suggestion
```

2020-12-11 15:36 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/AdminCardView.spec.ts
> +
```suggestion
```

2020-12-14 08:13 UTC, te4-david-jensen approved these changes
Looks good! 👍 :shipit:

2020-12-14 08:21 UTC, te4-adrian-almetun-smeds approved these changes
Looks good :+1: :shipit:

2020-12-14 08:38 UTC, merged