Test for adding book loan
itggot-TE4/Yabs pull request #444
Opened 2020-12-11 13:55 UTC by te4-alexander-kjellberg1

## ⚙️ What issue did you implement or fix?
Fixes #1

## 📜 Summary
- Fixed foobar in zoobar.
- Made foo better.

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

2020-12-11 14:03 UTC, te4-adrian-almetun-smeds commented
@te4-alexander-kjellberg1 can you see too that there is a issue regarding the commented out code :+1:

2020-12-11 14:16 UTC, te4-tintin-wihlborg requested changes
On line 7 in addLoan.js your request data-cy=book_barcode but you change the data-cy to book_barcode_return. Is that intended?

2020-12-11 14:16 UTC, te4-tintin-wihlborg commented on frontend/cypress/integration/addLoan.js
> +    //   cy.get('[data-cy=loan_data]').contains('aBarCode');
You sure we should keep this?

2020-12-11 14:21 UTC, te4-andre-skvarc requested changes

2020-12-11 14:21 UTC, te4-andre-skvarc commented on frontend/src/components/ReturnLoanComponent.vue
> +            data-cy="book_barcode_return"
Have you checked on this, so no other test is using ' data-cy="book_barcode" '? I don't really see the point of changing it.

2020-12-11 14:40 UTC, te4-alexander-kjellberg1 commented on frontend/cypress/integration/addLoan.js
> +    //   cy.get('[data-cy=loan_data]').contains('aBarCode');
Yes, once the functionality for adding loans is added, then this should be turnt back on. It is written in the description.

2020-12-11 14:42 UTC, te4-alexander-kjellberg1 commented on frontend/src/components/ReturnLoanComponent.vue
> +            data-cy="book_barcode_return"
book_barcode was on both of those data-cy's I changed one of them to have _retrun after it, so that I could used it almost as an id

2020-12-14 09:08 UTC, te4-alexander-kjellberg1 commented
> @te4-alexander-kjellberg1 can you see too that there is an issue regarding the commented out code 👍

Is it #430 ?

2020-12-14 09:14 UTC, te4-adrian-almetun-smeds commented
> > @te4-alexander-kjellberg1 can you see too that there is an issue regarding the commented out code 👍
> 
> Is it #430 ?

No not really, #430 is for the "admin" lend out page.
You should check that there is a issue for the code you commented out. So it would probably contains something along the lines of "When a user lends a book in the library the books should appear in table xyz"

2020-12-15 08:31 UTC, te4-alexander-kjellberg1 commented
> > > @te4-alexander-kjellberg1 can you see too that there is an issue regarding the commented out code 👍
> > 
> > 
> > Is it #430 ?
> 
> No not really, #430 is for the "admin" lend out page.
> You should check that there is a issue for the code you commented out. So it would probably contains something along the lines of "When a user lends a book in the library the books should appear in table xyz"

Why though? Isn't that and this pretty much the same?

2020-12-15 08:47 UTC, te4-adrian-almetun-smeds commented
> Why though? Isn't that and this pretty much the same?

Not necessarily, even though they share the same backend logic, they do only partly share the frontend logic. Thus we need to test each view separately to ensure that they work.

2020-12-15 08:48 UTC, te4-alexander-kjellberg1 commented
> > Why though? Isn't that and this pretty much the same?
> 
> Not necessarily, even though they share the same backend logic, they do only partly share the frontend logic. Thus we need to test each view separately to ensure that they work.

Okidoki, changing my changing my code a lil bit then :)

2020-12-15 09:08 UTC, te4-tintin-wihlborg approved these changes
Looks good!

2020-12-15 09:16 UTC, te4-andre-skvarc approved these changes
Nice work :shipit:

2020-12-15 09:16 UTC, merged