Refactured AddLoan and Navbar components
itggot-TE4/Yabs pull request #460
Opened 2020-12-14 11:21 UTC by te4-henrik-stahl

## ⚙️ What issue did you implement or fix?
Fixes #443

## 📜 Summary
- Refactured AddLoan component.
- Refactured Navbar component.

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2020-12-14 11:49 UTC, itggot-linus-styren requested changes
Great start, I noted some issues from previous team members in Yabs that have been overlooked unfortunately. I think this PR should take the opportunity to fix those issues. Should be combined with #422

@itggot-TE4/red-team any progress on said ticket?

2020-12-14 11:49 UTC, itggot-linus-styren commented on frontend/src/main.ts
> +import compsitionApi from '@vue/composition-api';
```suggestion
import compositionApi from '@vue/composition-api';
```

2020-12-14 11:49 UTC, itggot-linus-styren commented on frontend/src/main.ts
> +Vue.use(compsitionApi);
```suggestion
Vue.use(compositionApi);
```

2020-12-14 11:49 UTC, itggot-linus-styren commented on frontend/src/components/AddLoan.vue
> +    function focusRef(ref : any) : void { //eslint-disable-line @typescript-eslint/no-explicit-any
These functions need to be reviewed. Previous commiter of this file incorrectly assumed v-tooltip is the same as b-popover, however this is not the case. Most of the attributes for `v-tooltip` in the template are wrong. Also see https://github.com/itggot-TE4/Yabs/issues/443#issuecomment-743779884

Consider using `v-menu` instead.

2020-12-14 11:49 UTC, itggot-linus-styren commented on frontend/src/components/AddLoan.vue
> +      console.log(popoverShow)
Suggestion is to install recommended plugins in README.md so the editor will be configured to indent lines correctly automatically. Also read section "important" in https://github.com/itggot-TE4/Yabs/pull/452

2020-12-14 11:49 UTC, itggot-linus-styren commented on frontend/src/components/NavbarComponent.vue
> +        await UsersModule.signOut();
No need to use await here since this will dispatch the signOut action.

2020-12-14 11:49 UTC, itggot-linus-styren commented on frontend/src/components/NavbarComponent.vue
>          UsersModule.signOut();
Perhaps instead of signing out even if there is an exception, a snackbar displaying the error should be shown: https://vuetifyjs.com/en/components/snackbars/

2020-12-15 10:21 UTC, te4-david-jensen commented on frontend/src/components/AddLoan.vue
> +    })
```suggestion
    });
```

2020-12-15 10:22 UTC, te4-david-jensen commented on frontend/src/components/AddLoan.vue
> +      console.log(popoverShow)
```suggestion
    console.log(popoverShow)
```

2020-12-15 10:25 UTC, te4-david-jensen commented on frontend/src/components/AddLoan.vue
> +    function onShown(){
```suggestion
    function onShown(): void {
```

2020-12-15 13:12 UTC, itggot-linus-styren commented
To solve build issue, switch to type Wrapper<Vue> like done in https://github.com/itggot-TE4/Yabs/pull/434/files#diff-8acdea8bcc0a78d82be7c9723e54fdb6dad44f596301115e739380ed34950bd9L18-R19

Also because this PR is dragging on, consider creating new issue to use v-menu instead of v-tooltip. See review comments.

2020-12-15 13:12 UTC, Te4-Mahdi-Alizadah approved these changes
Looks good

2020-12-15 13:31 UTC, te4-alexander-kjellberg1 commented
Title for this pr is "Refactured AddLoan and Navbar components"

In the description are you mentioning that you fix #443 which points to the AddLoan component. But isn't there an issue for the Navbar component that you should add as another "fixes"-thingy?

2020-12-15 13:40 UTC, itggot-linus-styren commented
> Title for this pr is "Refactured AddLoan and Navbar components"
> 
> In the description are you mentioning that you fix #443 which points to the AddLoan component. But isn't there an issue for the Navbar component that you should add as another "fixes"-thingy?

Since the refactor for AddLoan is incomplete and the base for this PR is, maybe this PR should be abandoned and instead create a PR for fixing Navbar and work sepearelty on AddLoan in ticket #422.

I can assist in the workflow for doing this later today.

2020-12-15 14:55 UTC, closed without merging