Refactored UID
itggot-TE4/Yabs pull request #490
Opened 2020-12-14 13:43 UTC by te4-alexander-nylundgomes

## ⚙️ What issue did you implement or fix?
Fixes #489 

## 📜 Summary
- Refactored UID generated when backend is initialized.

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Could use a test

2020-12-14 14:03 UTC, te4-adrian-almetun-smeds requested changes
Just got a few thoughts.

2020-12-14 14:03 UTC, te4-adrian-almetun-smeds commented on backend/app/jobs/data_fetch_job.rb
> +      # @creation_time = Tue, 04 Feb 2020 01:38:22
```suggestion
```
Will this code bee needed again or should we just remove it?

2020-12-14 14:03 UTC, te4-adrian-almetun-smeds commented on backend/app/jobs/data_fetch_job.rb
> +      # year = "2020"
```suggestion
```

2020-12-14 14:03 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/ProfileView.vue
> +            :src="usersModule.currentUser.photo_path"
Does this display the actual photo associated to a account, or is this just a preparation for later?

2020-12-14 14:03 UTC, te4-adrian-almetun-smeds commented on frontend/src/store/modules/UsersModule.ts
> +          console.log(response);
```suggestion
```

2020-12-14 14:22 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +            :src="usersModule.currentUser.photo_path"
also if an admin uploads a photo from CigCanvas component:
https://github.com/itggot-TE4/Yabs/blob/a4e8ac4afd6d54c9d886a3c731796bf98d8a88c7/frontend/src/components/CigCanvas.vue#L283-L287

This will break if we update the path like this. Note that the photo should reflect a photo of the actual person, this way all students can have arbitrary profile pictures which may not correspond to the photo of the person on their card.

2020-12-15 08:14 UTC, te4-dennis-christensen approved these changes
Take a look at Adrian's and Linus' comments. Other than that it looks good to me!

2020-12-15 08:15 UTC, te4-alexander-nylundgomes commented on backend/app/jobs/data_fetch_job.rb
> +      # @creation_time = Tue, 04 Feb 2020 01:38:22
These are comments to explain the contents of the variables

2020-12-15 08:15 UTC, te4-alexander-nylundgomes commented on backend/app/jobs/data_fetch_job.rb
> +      # year = "2020"
Same as the other one, just comments

2020-12-15 08:22 UTC, te4-alexander-nylundgomes commented on frontend/src/views/ProfileView.vue
> +            :src="usersModule.currentUser.photo_path"
The image is the users image which they have for their connected google account. This, however, does not work because of security reasons and a generic blue image is shown instead. A new issue was created where the image is taken by a teacher. Consider it to be preperation.

2020-12-15 08:24 UTC, te4-alexander-nylundgomes commented on frontend/src/views/ProfileView.vue
> +            :src="usersModule.currentUser.photo_path"
Linus could you further explain where it could break and how? I'm not following.

2020-12-15 09:09 UTC, te4-adrian-almetun-smeds requested changes

2020-12-15 09:09 UTC, te4-adrian-almetun-smeds commented on backend/app/jobs/data_fetch_job.rb
> +      # @creation_time = Tue, 04 Feb 2020 01:38:22
But the variable `@create_time` isn't used in the function. Is this intended to actually be `year` ?

2020-12-15 09:09 UTC, te4-adrian-almetun-smeds commented on backend/app/jobs/data_fetch_job.rb
> +      # year = "2020"
Then we probably should place this one above the year definition

2020-12-15 09:11 UTC, te4-alexander-nylundgomes commented on backend/app/jobs/data_fetch_job.rb
> +      # @creation_time = Tue, 04 Feb 2020 01:38:22
Yes it is, person.creation_time

2020-12-15 09:11 UTC, te4-alexander-nylundgomes commented on backend/app/jobs/data_fetch_job.rb
> +      # year = "2020"
Agreed.

2020-12-15 09:19 UTC, te4-alexander-nylundgomes commented on backend/app/jobs/data_fetch_job.rb
> +      # @creation_time = Tue, 04 Feb 2020 01:38:22
Changed to person.creation_time for further understanding

2020-12-15 09:19 UTC, te4-adrian-almetun-smeds commented on backend/app/jobs/data_fetch_job.rb
> +      # @creation_time = Tue, 04 Feb 2020 01:38:22
But then it's `person.creation_time` not `@creation_time`

2020-12-15 09:22 UTC, te4-adrian-almetun-smeds requested changes

2020-12-15 09:22 UTC, te4-adrian-almetun-smeds commented on backend/app/jobs/data_fetch_job.rb
> +      # personcreation_time = Tue, 04 Feb 2020 01:38:22
```suggestion
      # person.creation_time = Tue, 04 Feb 2020 01:38:22
```

2020-12-15 09:26 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +            :src="usersModule.currentUser.photo_path"
> however, does not work because of security reasons and a generic blue image is shown instead

Is this what happens after this change? Anyhow if this is preparation work for another ticket, how does it relate to the acceptance criteria in #489 and #399 ? Shouldn't these changes be in another PR?

>could you further explain where it could break and how

Let me ask a question to you instead, how do we make sure the user has the same profile image as the image on their generated card (shown in #90)? Google account image can be changed by student to have an image of another student (an imposter!).

2020-12-15 10:23 UTC, te4-adrian-almetun-smeds approved these changes
:+1: Just check what DeepScan has to say

2020-12-15 10:26 UTC, itggot-linus-styren commented
@te4-alexander-nylundgomes please double check open conversations are resolved before merging and there is a plan of action.

2020-12-15 11:36 UTC, te4-alexander-nylundgomes commented on frontend/src/views/ProfileView.vue
> +            :src="usersModule.currentUser.photo_path"
Agreed. Removing file and fixing the file in a dedicated issue.

2020-12-15 11:49 UTC, itggot-linus-styren requested changes
Opps?

2020-12-15 11:49 UTC, itggot-linus-styren commented on backend/app/jobs/data_fetch_job.rb
> +        @user.update(name: person.name.full_name, uid: uid, klass: klass, email: person.emails[0]["address"], role: role, google_token: person.id, photo_path: person.thumbnail_photo_url)
Don't add photo_path in this PR

2020-12-15 11:49 UTC, itggot-linus-styren commented on backend/app/jobs/data_fetch_job.rb
> +        User.create(name: person.name.full_name, uid: uid, klass: klass, email: person.emails[0]["address"], role: role, google_token: person.id, photo_path: person.thumbnail_photo_url)
See above

2020-12-15 11:49 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> -</script>
I don't think you meant to delete this file, just reverting the change for photo path. Just do the following:
```
git checkout a4e8ac4afd6d54c9d886a3c731796bf98d8a88c7 frontend/src/views/ProfileView.vue
```

2020-12-16 13:55 UTC, closed without merging