User profile view and role display
itggot-TE4/Yabs pull request #491
Opened 2020-12-14 14:52 UTC by TE4-David-Sundqvist

## ⚙️ What issue did you implement or fix?
Fixes #419 
Fixes #375 

## 📜 Summary
- Fixed foobar in zoobar.
- Made foo better.

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

2020-12-14 14:59 UTC, itggot-linus-styren requested changes
Looks good, just some questions regarding the mentioned comments in referenced tickets. Do we need to rewrite the tests for profile?

Also see: https://github.com/itggot-TE4/Yabs/commit/f6e029c2871cec67df5c3447af93d2642b7b5bb6 and #332

2020-12-14 14:59 UTC, itggot-linus-styren commented on frontend/src/helpers/roleToText.ts
> +  let text = roleText[role];
potential bug here is that if you are both a teacher and admin (when role is set to 20) this will return undefined. Needs some safe check to make sure role is in roleText list, and also this should only display the role with highest importance. In practice this means finding the most significant set bit and getting the decimal value of it. See e.g https://www.geeksforgeeks.org/find-significant-set-bit-number/

2020-12-15 08:21 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/AdminUsersView.vue
> +    console.log(this.$route);
Vill du ha kvar console logs?

2020-12-15 08:21 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/AdminUsersView.vue
> +    console.log(this.$route);
```suggestion
```

2020-12-15 08:21 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/AdminUsersView.vue
> +    console.log(user.uid);
```suggestion
```

2020-12-15 10:38 UTC, Te4-Jacob-sandstrom approved these changes

2020-12-15 10:38 UTC, Te4-Jacob-sandstrom requested changes
Run git pull --rebase before push

2020-12-15 10:49 UTC, itggot-linus-styren reviewed
Looks good overall, just some suggestions to make the code more clear.

2020-12-15 10:49 UTC, itggot-linus-styren commented on frontend/src/helpers/roleToText.ts
> +  }
To me this code is a bit confusing. Maybe something like this could achieve the same result?
```suggestion
const rolesKeys : number[] = Object.keys(roleText);
const roles : string[] = rolesKeys.filter((
    bitwise) => role & bitwise).map(
    (bitwise) => roleText[bitwise])
```

2020-12-15 10:49 UTC, itggot-linus-styren commented on frontend/src/helpers/roleToText.ts
> +  return roleList.join(', ');
If we want to show all roles on card
```suggestion
  return roles.join(', '); 
```

2020-12-15 10:49 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +  private getUser():string {
Do we need to rewrite test `frontend/src/views/__tests__/ProfileView.spec.ts` ? Since that test assumes usersModule.currentUser will be displayed.

2020-12-15 13:10 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/ProfileView.vue
> +    return this.usersModule.all[this.$route.params.id];
Is there no better way of fetching a single user?

2020-12-15 13:14 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/ProfileView.vue
> +    return this.usersModule.all[this.$route.params.id];
Can we save the user to a variable instead of having this act as a function. This way we don´t have to isolate the current user from the users list every time we reference a user.

2020-12-15 16:00 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +    return this.usersModule.all[this.$route.params.id];
I suggest in this case to add a vuex getter and make a computed property calling the getter with this.$route.params.id as a parameter. Maybe it could be a new issue though.

2020-12-16 14:40 UTC, te4-adrian-almetun-smeds requested changes
Some thoughts. See below

2020-12-16 14:40 UTC, te4-adrian-almetun-smeds commented on frontend/src/types.ts
> +import { Action } from 'vuex';
Do we really need to import `Action` here?

2020-12-16 14:40 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/ProfileView.vue
> +    let id: number = parseInt(this.$route.params.id);
Is this ever reassigned? Should it be a `const` instead?

2020-12-16 14:40 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/ProfileView.spec.ts
> +    }, 1000);
Why is there a `setTimeout`?

2020-12-16 14:40 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/ProfileView.spec.ts
> +      expect(wrapper.text()).toMatch('TE4');
Would it not be preferable to extract "Test Jestsson" and "TE4" to a constant, to further DRY this

2020-12-16 14:46 UTC, Te4-Jacob-sandstrom commented on frontend/src/views/__tests__/ProfileView.spec.ts
> +    }, 1000);
because it works

2020-12-16 15:54 UTC, itggot-linus-styren commented
@TE4-David-Sundqvist seems like one command was missed before running `git reset` on this branch. You will need to rebase on top of develop before squashing the commits from this PR into one.

Please use `git reflog` to go back to before running `git reset` and then run `git reset --hard HEAD@{result from reflog}`. Finally follow the steps in https://github.com/itggot-TE4/Yabs/discussions/509 under "Cleaning up WIP/redundant commits" and create a new branch.

2020-12-16 16:00 UTC, Te4-Jacob-sandstrom requested changes
Fix git history

2020-12-16 16:06 UTC, itggot-linus-styren requested changes
@TE4-David-Sundqvist seems like one command was missed before running `git reset`/`git merge` on this branch. You will need to rebase on top of develop before squashing the commits from this PR into one.

Please use `git reflog` to go back to before running `git reset`/`git merge` and then run `git reset --hard HEAD@{result from reflog}`. Finally follow the steps in https://github.com/itggot-TE4/Yabs/discussions/509 under "Cleaning up WIP/redundant commits" and create a new branch.

2020-12-17 10:03 UTC, closed without merging