Feature/381 update users
itggot-TE4/Yabs pull request #498
Opened 2020-12-15 12:24 UTC by te4-alexander-nylundgomes

## ⚙️ What issue did you implement or fix?
Fixes #381 

## 📜 Summary
- Added ability for updating profile image
- Added ability to view image in users profile page

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Needs nav guards

2020-12-15 12:34 UTC, itggot-linus-styren reviewed
Some suggestions

2020-12-15 12:34 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +      alert('You have not selected a file!');
Instead of using alert probably better to use https://vuetifyjs.com/en/components/snackbars/

2020-12-15 12:34 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +      console.error(error);
see above

2020-12-15 12:34 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +    <v-card class="d-flex align-start justify-center pa-4 pt-7 pb-1">
Maybe this card should only be shown if the current user is an admin?

2020-12-15 12:59 UTC, te4-alexander-nylundgomes commented on frontend/src/views/ProfileView.vue
> +    <v-card class="d-flex align-start justify-center pa-4 pt-7 pb-1">
Good idea!

2020-12-15 12:59 UTC, te4-alexander-nylundgomes commented on frontend/src/views/ProfileView.vue
> +      alert('You have not selected a file!');
This would improve the quality of the design greatly. Will be implemented!

2020-12-15 15:01 UTC, te4-henrik-stahl requested changes
Looks good! Try to fix the linter issues reported by Github actions! ;)

2020-12-16 09:20 UTC, itggot-linus-styren requested changes
Looks good, please address the lint issues found by GA, see "Files changed". Do `yarn run lint`.

2020-12-16 09:20 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +      // TODO: show in notification to user
```suggestion
```

2020-12-16 09:20 UTC, itggot-linus-styren commented on frontend/src/views/ProfileView.vue
> +    // padding-bottom: 2.5vh;
```suggestion
```

2020-12-17 08:25 UTC, closed without merging