Refactored Start.vue
itggot-TE4/Yabs pull request #500
Opened 2020-12-15 12:50 UTC by te4-alexander-kjellberg

## ⚙️ What issue did you implement or fix?
Fixes #496 

## 📜 Summary
- Refactored Start.vue to Composition API. 
- Realised that LoadingIcon is never used => removed corresponding imports and references. 

## 📝 Type of change

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [x] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Adding tests wouldn't hurt...

2020-12-15 14:39 UTC, Te4-Mahdi-Alizadah approved these changes
That seems good.

2020-12-15 15:50 UTC, itggot-linus-styren commented on frontend/src/views/Start.vue
> +// }
Please consider removing this ;)

See: https://kentcdodds.com/blog/please-dont-commit-commented-out-code/

2020-12-16 12:50 UTC, te4-andre-skvarc requested changes
Solve the code that Linus mentioned! And it will be ready!

2020-12-16 13:40 UTC, TE4-Filip-Liljenberg approved these changes
Great succes!

2020-12-16 14:34 UTC, te4-andre-skvarc approved these changes
Now it's looking much better, approved! 👍

2020-12-16 14:35 UTC, merged