refactor/501 AdminView AdminUsers
itggot-TE4/Yabs pull request #503
Opened 2020-12-15 13:58 UTC by te4-alexander-kjellberg

## ⚙️ What issue did you implement or fix?
Fixes #501 

## 📜 Summary
- Refactored AdminView.vue
- Refactored AdminUsersView.vue

## 📝 Type of change

Please delete options that are not relevant.

- [x] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-12-15 15:21 UTC, te4-adrian-almetun-smeds requested changes
Looks promising!

2020-12-15 15:21 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/AdminUsersView.vue
> +    const search: string = '';
Do this one need to be reactive? In other terms, does the search function still work?

2020-12-15 15:21 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/Start.vue
> +// }
```suggestion
```

No need for that now

2020-12-16 09:27 UTC, Te4-Jacob-sandstrom requested changes
Please make sure that all tests pass before requesting a review

2020-12-16 11:43 UTC, te4-alexander-kjellberg commented
Anyone know how I can make these tests pass?

2020-12-16 15:27 UTC, te4-adrian-almetun-smeds commented
Closing in favour of #523

2020-12-16 15:27 UTC, closed without merging