return functionality for books in adminview
itggot-TE4/Yabs pull request #506
Opened 2020-12-15 14:41 UTC by TE4-Rasmus-Brednert

## ⚙️ What issue did you implement or fix?
Fixes #360 

## 📜 Summary
- Fixed functionality for returning books in adminview.

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

2020-12-15 14:44 UTC, te4-alexander-kjellberg approved these changes
Seems legit.

2020-12-15 14:53 UTC, te4-alexander-nylundgomes commented on frontend/src/views/AdminLoansView.vue
> +        <div style="margin-right: 50px">
Perhaps this should follow vue structure and be in the bottom in a style tag?

2020-12-15 14:53 UTC, te4-alexander-nylundgomes commented on frontend/src/views/AdminLoansView.vue
> +    <div style="margin-top: 50px">
Same as above

2020-12-15 14:54 UTC, te4-alexander-nylundgomes commented on frontend/src/views/AdminLoansView.vue
> -    LoanListComponent
Is LoanListComponent still in use? If not, perhaps the import of the component should be removed?

2020-12-15 14:55 UTC, te4-alexander-nylundgomes requested changes
Looks good but could use some structure

2020-12-17 09:03 UTC, TE4-Rasmus-Brednert commented on frontend/src/views/AdminLoansView.vue
> -    LoanListComponent
yes, it is in use.

2020-12-18 08:21 UTC, te4-alexander-nylundgomes approved these changes
Great!

2020-12-18 08:21 UTC, merged