Added tests for views/start.vue
itggot-TE4/Yabs pull request #550
Opened 2020-12-17 12:29 UTC by te4-david-jensen

# DO NOT MERGE YET
## ⚙️ What issue did you implement or fix?
Fixes #464 

## 📜 Summary
- Implemented Unit tests for views/start.vue

## 📝 Type of change
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Increase test coverage

2020-12-17 16:03 UTC, te4-david-jensen commented
Adding 'help wanted' as I can't make heads nor tails of how to fix the build errors in the integration tests.

2020-12-18 09:40 UTC, te4-david-jensen commented
the typeIssue has now been resolved

2020-12-18 11:17 UTC, itggot-linus-styren commented
@te4-david-jensen Can "DO NOT MERGE YET" be removed now?

2020-12-18 11:20 UTC, te4-david-jensen commented
> @te4-david-jensen Can "DO NOT MERGE YET" be removed now?

Forgot about that; removed it.

2020-12-18 11:38 UTC, Te4-Jacob-sandstrom approved these changes
Everything looks good

2020-12-18 12:11 UTC, TE4-Filip-Liljenberg commented on frontend/src/views/Start.vue
> +import { defineComponent, SetupContext } from '@vue/composition-api';
import ref

2020-12-18 12:14 UTC, TE4-Filip-Liljenberg requested changes

2020-12-18 12:14 UTC, TE4-Filip-Liljenberg commented on frontend/src/views/Start.vue
>      const size: string = 'lg';
Do, const size = ref('lg')

2020-12-18 12:14 UTC, TE4-Filip-Liljenberg commented on frontend/src/views/Start.vue
>      const loading: boolean = true;
const loading = ref(true);

2020-12-18 12:14 UTC, TE4-Filip-Liljenberg commented on frontend/src/views/Start.vue
>      const primary: string = 'primary';
const primary = ref('primary')

2020-12-18 12:14 UTC, TE4-Filip-Liljenberg commented on frontend/src/views/Start.vue
> +    const usersModule: UserModuleType = UsersModule;
const usersModule = ref(UserModuleType)

2020-12-18 12:28 UTC, itggot-linus-styren commented on frontend/src/views/Start.vue
> +    const usersModule: UserModuleType = UsersModule;
I suggest to remove this line completely and put UsersModule in return of setup directly

2020-12-18 12:46 UTC, te4-david-jensen commented on frontend/src/views/Start.vue
> +    const usersModule: UserModuleType = UsersModule;
How would I go about returning UserModule directly?

2020-12-18 12:46 UTC, TE4-Filip-Liljenberg approved these changes
Good job!

2020-12-18 12:52 UTC, merged