Refactored FindView and related components
itggot-TE4/Yabs pull request #551
Opened 2020-12-17 12:34 UTC by te4-alexander-kjellberg

## ⚙️ What issue did you implement or fix?
Fixes #531 

## 📜 Summary
- Refactored FindView.vue
- Refactored BookListComponent.vue

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Add tests and create types.

2020-12-17 13:43 UTC, te4-alexander-kjellberg1 commented on frontend/src/components/BookListComponent.vue
> +    const headers = [
Why not write it like this? This matches line 29 more.    

 const headers : object[] = [
      { text: 'Titel', value: 'title.name' },
      { text: 'Skick', value: 'condition' },
      { text: 'Sträckkod', value: 'barcode' },
 ];

2020-12-17 13:44 UTC, te4-jonathan-ronsten commented on frontend/src/components/BookListComponent.vue
> +      { text: 'Sträckkod', value: 'barcode' },
Change to 'Streckkod' Otherwise looks good

2020-12-17 13:45 UTC, te4-alexander-kjellberg1 commented on frontend/src/views/FindView.vue
> +    const users = ref(false as boolean);
Why use "false as boolean" and not "false : boolean"

2020-12-17 13:46 UTC, te4-jonathan-ronsten requested changes
Looks good overall, check comment

2020-12-17 13:51 UTC, te4-alexander-kjellberg commented on frontend/src/views/FindView.vue
> +    const users = ref(false as boolean);
It's the pro way

2020-12-17 13:53 UTC, te4-alexander-kjellberg commented on frontend/src/components/BookListComponent.vue
> +    const headers = [
It's the pro way!!

2020-12-18 08:49 UTC, te4-alexander-kjellberg1 approved these changes
Nice

2020-12-18 09:54 UTC, te4-jonathan-ronsten approved these changes
Looks good now! Nice job

2020-12-21 08:45 UTC, te4-david-jensen requested changes
Please clean up that commit history before merging

2020-12-21 08:52 UTC, closed without merging