LoanFormComponent are refactored
itggot-TE4/Yabs pull request #560
Opened 2020-12-18 10:40 UTC by TE4-Filip-Liljenberg

## ⚙️ What issue did you implement or fix?
Fixes #554

## 📜 Summary
- Refactored LoanFormComponent
- fixed test

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-18 11:52 UTC, te4-alexander-nylundgomes commented on frontend/src/components/LoanFormComponent.vue
> +    // user to recreate a loan
Might wanna remove these comments, they seem unnecessary 
```suggestion
    // Eventlistener that does not reload the page when executed, sets the lent by id to the 
    // Eventlistener that does not reload the page when executed, sets the lent by id to the 
    // Eventlistener that does not reload the page when executed, sets the lent by id to the 
    // current user that has been logged in and then rerenders the loan form for the 
    // current user that has been logged in and then rerenders the loan form for the 
    // current user that has been logged in and then rerenders the loan form for the 
    // user to recreate a loan 
    // user to recreate a loan 
    // user to recreate a loan 
```

2020-12-18 11:53 UTC, te4-alexander-nylundgomes requested changes
Looks good, just remove the comments

2020-12-18 15:08 UTC, te4-dennis-christensen approved these changes
Looks good, just check Alexanders comment

2020-12-21 14:41 UTC, te4-adrian-almetun-smeds approved these changes
Looks all good :+1:

2020-12-21 14:53 UTC, merged