refactored profile view
itggot-TE4/Yabs pull request #561
Opened 2020-12-18 11:06 UTC by TE4-Filip-Liljenberg

## ⚙️ What issue did you implement or fix?
Fixes #438

## 📜 Summary
- Refactored profile view

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-18 11:17 UTC, te4-adrian-almetun-smeds approved these changes
Looks good :+1:
Just check the failing tests

2020-12-18 11:17 UTC, te4-david-jensen commented
why remove type ```UsersModuleType```?

2020-12-18 11:27 UTC, Te4-Jacob-sandstrom reviewed
ERROR in /home/runner/work/Yabs/Yabs/frontend/src/views/__tests__/ProfileView.spec.ts(29,30):
29:30 'ProfileView' refers to a value, but is being used as a type here.
    27 |   it('Displays the correct name/role/class', () => {
    28 |     setTimeout(() => {
  > 29 |       const wrapper: Wrapper<ProfileView> = shallowFactory(ProfileView);
       |                              ^
    30 |   
    31 |       baseUser.role = 1;
    32 |       baseUser.uid = 1111;

change  Wrapper<ProfileView> to  Wrapper<Vue> in test file

2020-12-18 11:28 UTC, te4-david-jensen commented on frontend/src/types.ts
> -  allAsArray: User[];
Why remove this type?

2020-12-18 14:50 UTC, te4-david-jensen requested changes
Just make the final checks pass and it's good to go! (message me on discord if you want help)

2020-12-21 13:56 UTC, te4-david-jensen approved these changes
Looks good! :shipit:

2020-12-21 13:58 UTC, merged