Test/471 test for edit book view
itggot-TE4/Yabs pull request #580
Opened 2020-12-18 15:34 UTC by TE4-David-Sundqvist

## ⚙️ What issue did you implement or fix?
Fixes #471

## 📜 Summary
Added test to EditBookView

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change the way we use setTimeout

2020-12-18 15:38 UTC, te4-david-jensen approved these changes
Looks great! :shipit:

2020-12-18 15:53 UTC, te4-adrian-almetun-smeds reviewed
I don't understand all of this. Check my comment

2020-12-18 15:53 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +      expect(wrapper.text()).toMatch('korvmedmos');
This seems off to me. If `wrapper.text()` matches `1001` how is it supposed to match `korvmedmos` ?

2020-12-18 16:45 UTC, itggot-linus-styren commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +      expect(wrapper.text()).toMatch('korvmedmos');
toMatch is not the same as toBe so this is actually testing for a regex thus both of them will be true even though it is hard to read.

2020-12-18 16:52 UTC, itggot-linus-styren requested changes
Test looks good, needs to be rebased because of #575

2020-12-18 16:52 UTC, itggot-linus-styren commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +      expect(wrapper.find({name: 'BookStatusComponent'}).exists()).toBe(true);
I can't see BookStatusComponent in EditBookView.vue, also this branch should be rebased with develop since the component has been refactored to composition API and will break this test:
https://github.com/itggot-TE4/Yabs/commit/a15a874d6a9e1a071eac2fe711578d3eb6f2b9a0#diff-e869bc24d1e84e7c6ad89f2d0d6ac899e75a6ac785fdbf4d0e5b21292005efc3

2020-12-18 16:52 UTC, itggot-linus-styren commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +    setTimeout(() => {
Perhaps Vue.$nextTick works instead of using setTimeout

2020-12-18 17:14 UTC, TE4-David-Sundqvist commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +      expect(wrapper.find({name: 'BookStatusComponent'}).exists()).toBe(true);
That's actually because the BookConditionComponent.vue has it's name set to BookStatusComponent by whoever originally made the component, is it something that should be changed in this pr?
My tests still seem to pass fine after rebase?

2020-12-21 08:09 UTC, TE4-David-Sundqvist commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +    setTimeout(() => {
Vue.$nextTick doesn't exist Vue.nextTick didn't help.

2020-12-21 08:14 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +    setTimeout(() => {
Did you import vue?

2020-12-21 08:16 UTC, TE4-David-Sundqvist commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +    setTimeout(() => {
yes

2020-12-21 08:17 UTC, te4-adrian-almetun-smeds approved these changes
Test looks good. If it works after rebasing and you checked up on `nextTick` then LGTM. 👍

2020-12-21 08:20 UTC, itggot-linus-styren commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +    setTimeout(() => {
I think the root cause of the delay in this test is being of calling asynchronous vuex action. Looking at other tests these are usually mocked:
https://github.com/itggot-TE4/Yabs/blob/eb57194b1b807265bfe2bbcf40b094d8750c246a/frontend/src/components/__tests__/LoanFormComponent.spec.ts#L9-L15

Probably something similar could be done here.

2020-12-21 08:23 UTC, itggot-linus-styren commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +      expect(wrapper.find({name: 'BookStatusComponent'}).exists()).toBe(true);
Tests still pass but having different name for the component compared to file name violates coding standard, atleast create an issue for it to keep a note.

2020-12-21 08:57 UTC, TE4-David-Sundqvist commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +      expect(wrapper.find({name: 'BookStatusComponent'}).exists()).toBe(true);
Opened an issue: #582

2020-12-21 09:11 UTC, itggot-linus-styren approved these changes

2020-12-21 09:11 UTC, itggot-linus-styren commented on frontend/src/views/__tests__/EditBookView.spec.ts
> +    setTimeout(() => {
Since this is the case for several test suites, maybe it should be addressed in another issue. @itggot-TE4/yabs-team QA-team to resolve these problems.

2020-12-21 09:52 UTC, merged