refactor/581 AddLoan component
itggot-TE4/Yabs pull request #590
Opened 2020-12-21 12:08 UTC by te4-henrik-stahl

## ⚙️ What issue did you implement or fix?
Fixes #581

## 📜 Summary
- Refactored AddLoan Component

## 📝 Type of change
- [x] ✨ New featureor enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-21 12:17 UTC, te4-dennis-christensen approved these changes
Looks good

2020-12-21 12:25 UTC, te4-adrian-almetun-smeds requested changes
Looks good. There may be some tweaks that can be done. See my suggestions.

2020-12-21 12:25 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/AddLoan.vue
> +    let inputText = ref(''),
```suggestion
    const inputText = ref(''),
```

2020-12-21 12:25 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/AddLoan.vue
> +      menu = ref(false as boolean);
Is the `as boolean` required?

2020-12-21 12:25 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/AddLoan.vue
> +      loaned_by_id: 0,//eslint-disable-line camelcase
```suggestion
      loaned_by_id: 0, //eslint-disable-line camelcase
```

2020-12-21 12:30 UTC, itggot-linus-styren reviewed
Some comments, also added original author of component as reviewer

2020-12-21 12:30 UTC, itggot-linus-styren commented on frontend/src/components/AddLoan.vue
> +    let inputText = ref(''),
Prefer to use const here

2020-12-21 12:30 UTC, itggot-linus-styren commented on frontend/src/components/AddLoan.vue
> +      menu = ref(false as boolean);
"as boolean" is redundant, type is inferred by literal value.

2020-12-21 12:30 UTC, itggot-linus-styren commented on frontend/src/components/AddLoan.vue
> +        console.log(form);
Can be removed

2020-12-21 12:30 UTC, itggot-linus-styren commented on frontend/src/components/AddLoan.vue
> +        if (!!form.lent_by_id && !!form.loaned_by_id && !!form.book_id) {
```suggestion
        if (!Object.values(form.value).some(prop => prop === 0)) {
```
Somewhat more clean solution.

2020-12-21 14:18 UTC, te4-andre-skvarc requested changes
See what the other reviewers said and correct it!

2020-12-30 14:16 UTC, te4-adrian-almetun-smeds requested changes
Looks good. But please also check the previous comments and the linter errors. 
https://github.com/itggot-TE4/Yabs/pull/590#discussion_r546675896

2021-01-11 08:54 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/AddLoan.vue
> +        if (!Object.values(form.value).some(prop => prop === 0)) {
```suggestion
        if (!Object.values(form).some(prop => prop === 0)) {
```

2021-01-11 09:31 UTC, te4-henrik-stahl commented on frontend/src/components/AddLoan.vue
> +      menu = ref(false as boolean);
Im not 100% sure but i remember something about us needing it, but i could be wrong.

2021-01-11 11:15 UTC, te4-adrian-almetun-smeds approved these changes
Looks good to me. :+1: :shipit:

2021-01-11 11:15 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/AddLoan.vue
> +      menu = ref(false as boolean);
Shouldn't be needed though..

2021-01-11 11:15 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/AddLoan.vue
> +    const form: Ref < AddLoanForm > = ref ({
Didn't know you could do Ref as a type :+1:

2021-01-11 12:03 UTC, te4-henrik-stahl commented on frontend/src/components/AddLoan.vue
> +      menu = ref(false as boolean);
So should just change it to (false) or (null)?

2021-01-11 14:32 UTC, te4-andre-skvarc approved these changes
Good work Henrik!

2021-01-12 08:38 UTC, merged