Save all pictures button in admin/cards
itggot-TE4/Yabs pull request #595
Opened 2020-12-21 15:52 UTC by te4-dennis-christensen

## ⚙️ What issue did you implement or fix?
Fixes #420

## 📜 Summary
- Added a button to save all pictures

## 📝 Type of change
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
Don't know how, just doesn't feel like the best solution.

2020-12-21 16:02 UTC, te4-adrian-almetun-smeds requested changes
Looks good, I'd like one change though.

And yes the better solution would probably be to setup a rails route that accepts multiple updates at the same time, but that also sort of violates the RESTful API architecture. So there's both good and bad views on the current implementation.

2020-12-21 16:11 UTC, te4-dennis-christensen commented on frontend/src/components/CanvasContainer.vue
> +    let saveAllPictures: Ref<boolean> = ref(false);
fixed in latest commit

2020-12-21 16:35 UTC, te4-adrian-almetun-smeds approved these changes
I approve :+1:

2021-01-11 08:34 UTC, te4-andre-skvarc approved these changes
Looks good!

2021-01-11 08:58 UTC, merged