Loan form Expire date input added
itggot-TE4/Yabs pull request #602
Opened 2021-01-11 09:25 UTC by TE4-Sebastian-Utbult

## ⚙️ What issue did you implement or fix?
Fixes #1

## 📜 Summary
- Fixed foobar in zoobar.
- Made foo better.

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

2021-01-11 09:28 UTC, te4-adrian-almetun-smeds commented
Try running `git reset --soft HEAD~2` and then do `git add frontend/cypress/integration/loanBooks.js` `frontend/src/components/LoanFormComponent.vue` `frontend/src/types.ts`

2021-01-11 09:53 UTC, te4-david-jensen commented
This branch is (as of writing) 206 commits behind 'develop'. I believe you'll need to get it up to date in order for these checks to pass.

2021-01-12 08:39 UTC, te4-adrian-almetun-smeds requested changes
Some lint errors but, should be a quick fix

2021-01-12 08:39 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/LoanFormComponent.vue
> +      book_id: 0,
```suggestion
      book_id: 0, //eslint-disable-line camelcase
```

2021-01-12 08:39 UTC, te4-adrian-almetun-smeds commented on frontend/src/types.ts
> +  expiration_date: string;
```suggestion
  expiration_date: string; //eslint-disable-line camelcase
```

2021-01-13 07:29 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/LoanFormComponent.vue
> +            @change="save"
Save doesn't seem to be defined in this component. Should it be?

2021-01-13 09:02 UTC, TE4-Rasmus-Brednert requested changes
Look at the failed checks, then you're ready to go.

2021-01-14 09:07 UTC, te4-andre-skvarc requested changes
Looks better now, but check the test so they pass. I recommend doing a rebase and then push up the code again.

2021-01-14 09:21 UTC, te4-andre-skvarc approved these changes
Looks good now!  :shipit:

2021-01-14 09:27 UTC, itggot-linus-styren commented
Why are there two almost identical methods with different types:
https://github.com/itggot-TE4/Yabs/blob/51765cf64d7dc17a2e726d6cc67a76b0d3936f65/frontend/src/services/api/loans.ts#L14-L28

The first one is using LoanForm and the other one is using AddLoanForm?

2021-01-14 09:27 UTC, TE4-Rasmus-Brednert approved these changes
Nice!

2021-01-14 09:34 UTC, te4-adrian-almetun-smeds commented
> Why are there two almost identical methods with different types:
> https://github.com/itggot-TE4/Yabs/blob/51765cf64d7dc17a2e726d6cc67a76b0d3936f65/frontend/src/services/api/loans.ts#L14-L28
> 
> The first one is using LoanForm and the other one is using AddLoanForm?
> 
> Maybe the second one can be removed to resolve codeclimate complaint. It doesn't seem to be used anywhere:
> ![image](https://user-images.githubusercontent.com/23553553/104571490-7202ea00-5653-11eb-889e-71ab3c606bbb.png)

Good question. A new issue has been open regarding said issue since it's outside of the scope of this PR.

2021-01-14 09:35 UTC, te4-adrian-almetun-smeds approved these changes

2021-01-14 09:35 UTC, merged