Enhancement/421 rework card generation
itggot-TE4/Yabs pull request #634
Opened 2021-01-13 13:01 UTC by te4-alexander-nylundgomes

## ⚙️ What issue did you implement or fix?
Fixes #421 

## 📜 Summary
- Reworked syntax and made it more readable
- Reworked cards so it looks nicer
- Added. functionality to buttons

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Further rework could be done with admin/cards. There needs to be functionality to set exp date for the cards being generated.

2021-01-13 14:03 UTC, itggot-linus-styren requested changes
"i deserve a raise" yup, if you fix all the feedback ;)

2021-01-13 14:03 UTC, itggot-linus-styren commented on frontend/src/components/CigCanvas.vue
> +        let scale = 15;
can this be expressed as a mathematical formula instead based on width and height to avoid hardcoding this?

2021-01-13 14:03 UTC, itggot-linus-styren commented on frontend/src/components/CigCanvas.vue
> +        snackbarText.value = `Successfully updated user ${name.value}!`;
Use swedish instead of english

2021-01-13 14:03 UTC, itggot-linus-styren commented on frontend/src/components/CigCanvas.vue
> +        snackbarText.value = `Failed to update user: ${name.value}. Please try again`;
See above

2021-01-13 14:03 UTC, itggot-linus-styren commented on frontend/src/components/__tests__/CardFormComponent.spec.ts
> +    expect(wrapper.find('[data-cy="file-input"]')).toBeTruthy();
What does this test do? Can it be changed to test some behavior?

2021-01-13 14:03 UTC, itggot-linus-styren commented on frontend/src/views/AdminCardsView.vue
> +      console.log(sendImages);
Avoid commiting console.log :)

2021-01-13 14:03 UTC, itggot-linus-styren commented on frontend/src/views/AdminCardsView.vue
> +        downloadAll.value = false;
nice

2021-01-13 14:04 UTC, itggot-linus-styren commented on frontend/src/components/CigCanvas.vue
> +        Close
https://github.com/itggot-TE4/Yabs/discussions/504#discussioncomment-208640_

2021-01-13 14:07 UTC, te4-adrian-almetun-smeds reviewed
Will await next set of changes before completing my review.

2021-01-14 08:44 UTC, Te4-Jacob-sandstrom commented on frontend/src/components/CigCanvas.vue
> +        let scale = 15;
It probably can but this works and trying to make it scale with width and height would probably take more time than it's worth. I can create an issue for it to be done later.

2021-01-14 08:50 UTC, itggot-linus-styren commented on frontend/src/components/CigCanvas.vue
> +        let scale = 15;
Maybe add a comment with a link to the issue on this line for future context

2021-01-14 08:51 UTC, te4-alexander-nylundgomes commented on frontend/src/components/CigCanvas.vue
> +        let scale = 15;
Will do.

2021-01-14 08:58 UTC, itggot-linus-styren commented on frontend/src/components/__tests__/CardFormComponent.spec.ts
> +    expect(wrapper.find('[data-cy="file-input"]')).toBeTruthy();
In this case maybe adding a snapshot test would be best instead of only searching for the file-input tag. For reference this seems to be the way of testing VFileInput: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.ts#L155-L163

However, since it's already tested in the original vuetify package I see no reason why it needs to be tested here also unless specific behavior when a file is selected should be tested.

2021-01-14 09:00 UTC, itggot-linus-styren submitted a review, later dismissed
you shall be given a raise

2021-01-14 09:14 UTC, te4-adrian-almetun-smeds requested changes
A good revamp :+1:
But I have a few comments.

Also given the workflow implemented in this PR, I can't seem to figure out when the cards are saved to the backend. Is it when I press save on each individual card or is it when I select a user from the dropdown, or when?

2021-01-14 09:14 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/CigCanvas.vue
> +        Close
Language

2021-01-14 09:14 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/CigCanvas.vue
>      let name: Ref<string> = ref('');
Type definition seems redundant.
```suggestion
    let name = ref('');
```

2021-01-14 09:14 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/CigCanvas.vue
> +    let snackbar: Ref<boolean> = ref(false);
Same as above

2021-01-14 09:14 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/__tests__/CardFormComponent.spec.ts
> +// import BooksModule from '@/store/modules/BooksModule';
```suggestion
```

2021-01-14 09:22 UTC, Te4-Jacob-sandstrom commented
> A good revamp 👍
> But I have a few comments.
> 
> Also given the workflow implemented in this PR, I can't seem to figure out when the cards are saved to the backend. Is it when I press save on each individual card or is it when I select a user from the dropdown, or when?

This is not implemented yet see #628

2021-01-14 09:58 UTC, te4-adrian-almetun-smeds reviewed
Other than that E2E test it looks good :+1:

2021-01-14 10:33 UTC, te4-adrian-almetun-smeds approved these changes
Looks good. :+1: LGTM

2021-01-14 12:10 UTC, te4-jonathan-ronsten approved these changes
Couldn't find anything wrong now. Good job!

2021-01-14 12:10 UTC, merged