Implemented unit testing for FindView.vue
itggot-TE4/Yabs pull request #635
Opened 2021-01-13 13:20 UTC by te4-david-jensen

## ⚙️ What issue did you implement or fix?
Fixes #472 

## 📜 Summary
- Implemented unit tests for FindView.vue

## 📝 Type of change
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
## ✅ Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Improve coverage and find out a way to test views less closely to implementation.

2021-01-13 13:36 UTC, te4-adrian-almetun-smeds approved these changes

2021-01-13 13:36 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/FindView.spec.ts
> +    expect(wrapper.html()).not.toBe('');
Can't we check it against a snapshot as well, to ensure the correct content. It'll probably have to use `factory` instead tho.

2021-01-13 13:36 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/FindView.spec.ts
> +      if (/Users|Loans|Books/.test(chipStubs.at(i).text())) {
Could you add a comment explaining what this checks?

2021-01-13 13:44 UTC, te4-adrian-almetun-smeds requested changes
Check previous comment.

2021-01-13 14:33 UTC, te4-andre-skvarc requested changes
Looks good, but I would also agree on that we need a some comments to really understand this test!

2021-01-14 08:25 UTC, te4-david-jensen commented on frontend/src/views/__tests__/FindView.spec.ts
> +    expect(wrapper.html()).not.toBe('');
Added a comparison to snapshot. It did not require `factory` to run. Was there any particular reason as to why `factory` would be better than `shallowFactory` here?

2021-01-14 08:26 UTC, te4-david-jensen commented on frontend/src/views/__tests__/FindView.spec.ts
> +      if (/Users|Loans|Books/.test(chipStubs.at(i).text())) {
I have added a comment to explain it.

2021-01-14 08:28 UTC, te4-adrian-almetun-smeds requested changes
Greatly improving the previous test case. Check my comments for additional feedback.

2021-01-14 08:28 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/FindView.spec.ts
> +describe('Start.vue', () => {
Wrong file name. You'll need to regenerate the snapshot after changing this.

2021-01-14 08:28 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/FindView.spec.ts
> +    expect(wrapper.html()).not.toBe('');
Did you try using `factory` instead to see what is most appropriate? We should strive to stubb as many of the child-components as possible.

2021-01-14 09:04 UTC, te4-david-jensen commented on frontend/src/views/__tests__/FindView.spec.ts
> +    expect(wrapper.html()).not.toBe('');
After some research I've found that since this is only a unit test for `FindView.vue` it would be beyond the scope of this issue to use `factory` as the difference of using factory would be using `mount` instead of `shallowMount`. This would then render the child components in full, as opposed to as stubs. It is therefore my belief as mentioned that this would be excessive and beyond the scope of a unit test for `FindView.vue`.

2021-01-14 09:08 UTC, te4-david-jensen commented on frontend/src/views/__tests__/FindView.spec.ts
> +    expect(wrapper.html()).not.toBe('');
Thoughts on this?

2021-01-14 09:17 UTC, te4-adrian-almetun-smeds commented on frontend/src/views/__tests__/FindView.spec.ts
> +    expect(wrapper.html()).not.toBe('');
Sounds good. Just checking :+1:

2021-01-14 09:44 UTC, te4-adrian-almetun-smeds approved these changes
Yup, another good test. :+1:

2021-01-14 09:44 UTC, te4-andre-skvarc approved these changes
Nicely done!

2021-01-14 09:48 UTC, merged