Reworked EditBookView
itggot-TE4/Yabs pull request #656
Opened 2021-01-14 15:15 UTC by te4-alexander-kjellberg

## ⚙️ What issue did you implement or fix?
Fixes #641 

## 📜 Summary
- Reworked EditBookView.vue  and BookConditionComponent.vue so that it no longer looks terrible and follows the general style of the project. 
- Changed routing in router.ts
- Changed BookForm in types.ts to support more data (notes). 
- Translated some words from english to swedish. 
- Had to translate a word in AdminBooksView.spec.ts for the test to pass. 

## 📝 Type of change

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-01-15 08:05 UTC, TE4-David-Sundqvist commented on frontend/src/components/ListComponent.vue
> +      console.log(item);
Do we still need to log this?

2021-01-15 08:06 UTC, TE4-David-Sundqvist commented on frontend/src/store/modules/BooksModule.ts
> +          console.log(response);
Do we still need to log this?

2021-01-15 08:10 UTC, TE4-David-Sundqvist commented on frontend/src/views/EditBookView.vue
> -    <v-img
Are we not supposed to have an image or?

2021-01-15 08:15 UTC, TE4-David-Sundqvist requested changes
Generally looks good! See if you can remove the logs though.

2021-01-15 09:25 UTC, te4-alexander-kjellberg1 approved these changes

2021-01-15 10:03 UTC, te4-alexander-kjellberg commented on frontend/src/components/ListComponent.vue
> +      console.log(item);
Yes! It's very important for the site to work. Don't know why, but DON'T remove it!

2021-01-15 10:04 UTC, te4-alexander-kjellberg commented on frontend/src/views/EditBookView.vue
> -    <v-img
Not really, but it can be easily added in the future.

2021-01-15 10:24 UTC, te4-adrian-almetun-smeds requested changes
Looks good. Just one thing.

2021-01-15 10:24 UTC, te4-adrian-almetun-smeds commented on frontend/src/components/ListComponent.vue
> +    // route kallas på med argumenten item. Item innehåller barcode för den som klickas på [?]
```suggestion
    // route is called with the arguments event and item. Item contains the barcode of the current book
```

2021-01-15 13:34 UTC, te4-adrian-almetun-smeds approved these changes
Sounds good :+1:

2021-01-19 08:31 UTC, itggot-linus-styren approved these changes
Merging PR in preparation for next year

2021-01-19 08:31 UTC, merged