Renamed the wrongfully named variable
itggot-TE4/Yabs pull request #719
Opened 2021-12-10 10:32 UTC by ntijoh-evelina-karlsson

## ⚙️ What issue did you implement or fix?
Fixes #582 

## 📜 Summary
- Changed BookStatusComponent variable name to BookConditionComponent, accordingly to the file name.

## 📝 Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-10 13:21 UTC, ntijoh-daniel-berg requested changes

2021-12-10 13:21 UTC, ntijoh-daniel-berg commented on frontend/src/views/__tests__/EditBookView.spec.ts
>    it('BooksStatusComponent exists', () => {
The test still refers to bookStatusComponent

2021-12-10 14:15 UTC, ntijoh-evelina-karlsson commented on frontend/src/views/__tests__/EditBookView.spec.ts
>    it('BooksStatusComponent exists', () => {
Fixed!!

2021-12-10 14:29 UTC, ntijoh-daniel-berg approved these changes

2021-12-13 09:24 UTC, ntijoh-axel-ostan approved these changes
nice

2021-12-13 09:25 UTC, merged