Fixed self-loan component
itggot-TE4/Yabs pull request #776
Opened 2021-12-15 10:24 UTC by ntijoh-evelina-karlsson

## ⚙️ What issue did you implement or fix?
Fixes #725 

## 📜 Summary
- Fixed style and function for the self loan menu. The code was reworked entirely due to old code being complicated and messy.  

## 📝 Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-15 10:25 UTC, ntijoh-my-lovell approved these changes
great work guys

2021-12-15 10:27 UTC, ntijoh-nikki-andersson approved these changes

2021-12-15 10:30 UTC, ntijoh-Erik-Albinsson requested changes
According to the projects code standard, 'singe quotes' should be used in frontend

2021-12-15 12:33 UTC, ntijoh-evelina-karlsson commented
> According to the projects code standard, 'singe quotes' should be used in frontend

It is not possible to use single quotes in the vuetify tags.

2021-12-15 13:42 UTC, ntijoh-Erik-Albinsson approved these changes

2021-12-15 13:46 UTC, Linkaan commented
This PR is 5 commits behind develop, consider merging with develop to make sure all checks pass:
```bash
git merge develop
```

2021-12-15 13:54 UTC, ntijoh-linus-bjorken approved these changes

2021-12-15 15:17 UTC, Linkaan commented
Make sure to update develop before merging with
git checkout develop
git pull

Alternatively you could run
git fetch --all
git merge origin/develop

2021-12-16 08:24 UTC, ntijoh-linus-bjorken approved these changes

2021-12-16 08:30 UTC, ntijoh-david-roman approved these changes

2021-12-16 08:30 UTC, ntijoh-nikki-andersson commented on frontend/src/components/AddLoanComponent.vue
> +              horizontal=""
Empty field?

2021-12-16 08:31 UTC, ntijoh-nikki-andersson approved these changes

2021-12-16 08:32 UTC, merged