Enhancement/756 scss codestandard
itggot-TE4/Yabs pull request #794
Opened 2021-12-16 12:30 UTC by ntijoh-david-roman

## ⚙️ What issue did you implement or fix?
Fixes #756

## 📜 Summary
- Fixed scss code standard for all the components and views.

## 📝 Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-16 12:48 UTC, ntijoh-axel-ostan approved these changes

2021-12-16 13:51 UTC, ntijoh-evelina-karlsson requested changes
Add ; to all css tags for consistency, even if it works without ; on the last one

2021-12-17 10:22 UTC, ntijoh-evelina-karlsson approved these changes
good!

2021-12-17 11:49 UTC, ntijoh-Erik-Albinsson approved these changes

2021-12-17 11:51 UTC, ntijoh-evelina-karlsson approved these changes

2021-12-17 11:51 UTC, merged